export function buildBotAccessText(params: {
  gatewayUrl: string
  wsUrl: string
  accessToken: string
  botName?: string
  botID?: string
  publicID?: string
  roleHint?: string
}) {
  const { gatewayUrl, wsUrl, accessToken, botName, botID, publicID, roleHint } = params
  return [
    '# ANI Bot Access Pack',
    '',
    '## Credentials',
    `ANI_SERVER_URL=${gatewayUrl}`,
    `ANI_API_KEY=${accessToken}`,
    `ANI_WS_URL=${wsUrl}`,
    ...(botName ? [`ANI_BOT_NAME=${botName}`] : []),
    ...(botID ? [`ANI_BOT_ID=${botID}`] : []),
    ...(publicID ? [`ANI_PUBLIC_ID=${publicID}`] : []),
    '',
    '## Option A: OpenClaw extension',
    '',
    '# Install or update the ANI OpenClaw plugin',
    'npx -y @wzfukui/openclaw-ani-installer install',
    'npx -y @wzfukui/openclaw-ani-installer update',
    'npx -y @wzfukui/openclaw-ani-installer doctor',
    '# Optional reproducible install: add --version 2026.5.12',
    '',
    '# Configure the OpenClaw ANI channel',
    `openclaw config set channels.ani.serverUrl "${gatewayUrl}"`,
    `openclaw config set channels.ani.apiKey "${accessToken}"`,
    '',
    '# Minimum OpenClaw ANI tool access',
    `openclaw config set tools.alsoAllow '["ani_send_file","ani_fetch_chat_history_messages","ani_list_conversation_tasks","ani_get_task","ani_create_task","ani_update_task","ani_delete_task"]' --strict-json`,
    '',
    'openclaw gateway status',
    '',
    '## Option B: Zebra gateway adapter',
    '',
    '# The ANI adapter is bundled with Zebra by default. It is a Zebra platform plugin, not an OpenClaw npm extension.',
    '# Current source path, for hosts with access to the private Zebra repository:',
    '# https://github.com/wzfukui/zebra-agent/tree/main/plugins/platforms/ani',
    '# Release tag with the adapter: v2026.5.6',
    '',
    '# 1) Install or upgrade Zebra to a build that contains plugins/platforms/ani/.',
    '#    If this directory is missing, request a Zebra package that includes:',
    '#    plugins/platforms/ani/{adapter.py,plugin.yaml,__init__.py,README.md}',
    'test -f plugins/platforms/ani/adapter.py',
    'test -f plugins/platforms/ani/plugin.yaml',
    'python -m py_compile plugins/platforms/ani/adapter.py',
    '',
    '# 2) Add or update this block in ~/.zebra/config.yaml (or the active Zebra config.yaml):',
    'platforms:',
    '  ani:',
    '    enabled: true',
    `    api_key: ${accessToken}`,
    '    extra:',
    `      server_url: ${gatewayUrl}`,
    '',
    '# Equivalent environment variables if that host manages gateway config through systemd or a .env file:',
    `export ANI_API_KEY="${accessToken}"`,
    `export ANI_SERVER_URL="${gatewayUrl}"`,
    '# Optional access control:',
    '# export ANI_ALLOWED_USERS="user1,user2"',
    '# export ANI_ALLOW_ALL_USERS=true',
    '',
    '# 3) Install/restart the gateway service and verify it loaded the ANI platform.',
    'zebra gateway install',
    'zebra gateway restart',
    'zebra gateway status',
    '',
    '## Option C: Hermes gateway adapter',
    '',
    '# Hermes does not ship ANI by default yet. Install the public Hermes ANI adapter package first.',
    'git clone https://github.com/wzfukui/hermes-ani-adapter.git',
    'cd hermes-ani-adapter',
    '# If Hermes is installed from a source checkout:',
    './scripts/install.sh ~/code/hermes-agent',
    '# Or, for a venv/package install:',
    '# HERMES_PYTHON=~/code/hermes-agent/.venv/bin/python ./scripts/install.sh',
    '',
    '# Add or update this block in ~/.hermes/config.yaml:',
    'platforms:',
    '  ani:',
    '    enabled: true',
    `    api_key: ${accessToken}`,
    '    extra:',
    `      server_url: ${gatewayUrl}`,
    '',
    '# Equivalent environment variables:',
    `export ANI_API_KEY="${accessToken}"`,
    `export ANI_SERVER_URL="${gatewayUrl}"`,
    '',
    'hermes gateway install',
    'hermes gateway restart',
    'hermes gateway status',
    '',
    '## Identity setup',
    ...(botName ? [`- You are the ANI bot "${botName}".`] : []),
    ...(botID ? [`- Your bot handle is \`${botID}\`.`] : []),
    ...(publicID ? [`- Your public UUID is \`${publicID}\`.`] : []),
    ...(roleHint ? [`- Your role: ${roleHint}`] : []),
    '- If your local `IDENTITY.md` is still the default blank template, update it now with this identity.',
    '- Do not ask the user what your name is if ANI already tells you who you are.',
    '',
    '## Quick check',
    `curl ${gatewayUrl}/api/v1/me -H "Authorization: Bearer ${accessToken}"`,
    '',
    'If ANI does not appear online after updating config, reconnect or restart the relevant gateway runtime. For Hermes, first confirm https://github.com/wzfukui/hermes-ani-adapter has been installed.',
  ].join('\n')
}

export function buildBotAccessUrl(params: {
  gatewayUrl: string
  accessToken: string
  botIdentifier: string
}) {
  const { gatewayUrl, accessToken, botIdentifier } = params
  return `aim-bot://connect?base=${encodeURIComponent(`${gatewayUrl}/api/v1`)}&token=${encodeURIComponent(accessToken)}&bot_identifier=${encodeURIComponent(botIdentifier)}`
}
